services:
  postgres:
    image: "postgres:13"
    container_name: cars_db
    ports:
      - 5430:5432
    environment:
      POSTGRES_DB: cars
      POSTGRES_PASSWORD: ngru_postgres
      POSTGRES_USER: ngru
    volumes:
      - postgres:/var/lib/postgresql/data/

  api:
    container_name: ngru_api
    build: ./src/
    command: ["gunicorn", "core.asgi:application", "-k", "uvicorn.workers.UvicornWorker", "-w", "2", "-b", ":8010"]
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - ./logs:/app/logs/
    ports:
      - 8010:8010
    environment:
      DJANGO_KEY: 'nb-=b1lif_low2c#w&!ly9($u68k$oamnv7u2mpu5!0%tmv+5)'
      DB_NAME: cars
      DB_TEST_NAME: cars_test
      DB_USER: ngru
      DB_PASSWORD: ngru_postgres
      DB_PORT: 5432
      DB_HOST: postgres
      DEBUG: 'True'

volumes:
  postgres:

networks:
  default:
